# Generated by Django 4.2.8 on 2023-12-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='default-slug', max_length=255, unique=True)),
                ('icon', models.CharField(default='img/standard_folder_icon.svg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField(default='default-slug', max_length=255, unique=True)),
                ('icon', models.CharField(default='img/standard_file_icon.svg', max_length=100)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.directory')),
            ],
        ),
    ]
